# Generated by Django 3.0.7 on 2020-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200620_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
