# Generated by Django 3.0.7 on 2020-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
